# Generated by Django 5.2.6 on 2025-09-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0015_availability_healthcare_service_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('endpoint', '0007_endpoint_healthcare_service'),
        ('organization', '0005_remove_organization_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('alias', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('instance', 'Instance'), ('kind', 'Kind')], max_length=16, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='components.address')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('endpoint', models.ManyToManyField(blank=True, related_name='locations', to='endpoint.endpoint')),
                ('managingOrganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='organization.organization')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('operationalStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_operational_status', to='components.coding')),
                ('partOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='location.location')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='LocationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='location.location')),
            ],
            options={
                'db_table': 'location_position',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['status'], name='location_status_f5d5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='location_name_5738e6_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['managingOrganization'], name='location_managin_673363_idx'),
        ),
    ]
