# Generated by Django 5.2.6 on 2025-09-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationqualification',
            name='identifier',
        ),
    ]
