# Generated by Django 5.2.6 on 2025-09-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organizationqualification_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
    ]
