# Generated by Django 5.2.6 on 2025-09-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organization_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='endpoint',
        ),
    ]
