# Generated by Django 5.2.6 on 2025-09-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0014_attachment_extendedcontactdetail'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0005_remove_organization_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('extraDetails', models.TextField(blank=True, null=True)),
                ('appointmentRequired', models.BooleanField(blank=True, null=True)),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('offeredIn', models.ManyToManyField(blank=True, related_name='offered_services', to='healthcareservice.healthcareservice')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_services', to='components.attachment')),
                ('providedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_healthcare_services', to='organization.organization')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
            ],
            options={
                'db_table': 'healthcare_service',
            },
        ),
        migrations.CreateModel(
            name='HealthcareServiceEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_service_eligibilities', to='components.codeableconcept')),
                ('healthcare_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='healthcareservice.healthcareservice')),
            ],
            options={
                'db_table': 'healthcare_service_eligibility',
            },
        ),
        migrations.AddIndex(
            model_name='healthcareservice',
            index=models.Index(fields=['active'], name='healthcare__active_0bb347_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcareservice',
            index=models.Index(fields=['name'], name='healthcare__name_77a7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcareservice',
            index=models.Index(fields=['providedBy'], name='healthcare__provide_d4e1c4_idx'),
        ),
    ]
