# Generated by Django 5.2.6 on 2025-09-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_availability_healthcare_service_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('endpoint', '0007_endpoint_healthcare_service'),
        ('healthcareservice', '0001_initial'),
        ('organization', '0005_remove_organization_endpoint'),
        ('practitioner', '0004_remove_practitionerrole_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareservice',
            name='endpoint',
            field=models.ManyToManyField(blank=True, related_name='healthcare_services', to='endpoint.endpoint'),
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='practitioner_roles',
            field=models.ManyToManyField(blank=True, related_name='healthcare_services', to='practitioner.practitionerrole'),
        ),
        migrations.AddIndex(
            model_name='healthcareservice',
            index=models.Index(fields=['appointmentRequired'], name='healthcare__appoint_b431a3_idx'),
        ),
    ]
