# Generated by Django 5.2.6 on 2025-09-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareservice', '0002_healthcareservice_endpoint_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareservice',
            name='coverageArea',
            field=models.ManyToManyField(blank=True, related_name='coverage_healthcare_services', to='location.location'),
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='healthcare_services', to='location.location'),
        ),
    ]
