# Generated by Django 5.2.3 on 2025-09-17 13:50

import components.reference
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0018_address_patient_address_related_person_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitedArtifactRelatesTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('documentation', 'Documentation'), ('citation', 'Citation'), ('predecessor', 'Predecessor'), ('successor', 'Successor'), ('derived-from', 'Derived From'), ('depends-on', 'Depends On'), ('composed-of', 'Composed Of'), ('part-of', 'Part Of'), ('cites', 'Cites'), ('cited-by', 'Cited By')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('resource', components.reference.CanonicalField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'cited_artifact_relates_to',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactStatusDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('actual', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cited_artifact_status_date',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'cited_artifact_title',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cited_artifact_version',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactWebLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cited_artifact_web_location',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('versionAlgorithmString', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired'), ('unknown', 'Unknown')], max_length=32)),
                ('experimental', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('copyrightLabel', models.CharField(blank=True, max_length=128, null=True)),
                ('approvalDate', models.DateField(blank=True, null=True)),
                ('lastReviewDate', models.DateField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, related_name='authored_metadata_resources', to='components.contactdetail')),
                ('contact', models.ManyToManyField(blank=True, related_name='canonical_resources', to='components.contactdetail')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('editor', models.ManyToManyField(blank=True, related_name='edited_metadata_resources', to='components.contactdetail')),
                ('effectivePeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='components.period')),
                ('endorser', models.ManyToManyField(blank=True, related_name='endorsed_metadata_resources', to='components.contactdetail')),
                ('identifier', models.ManyToManyField(blank=True, related_name='canonical_resources', to='components.identifier')),
                ('jurisdiction', models.ManyToManyField(blank=True, related_name='canonical_resources', to='components.codeableconcept')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('reviewer', models.ManyToManyField(blank=True, related_name='reviewed_metadata_resources', to='components.contactdetail')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
                ('topic', models.ManyToManyField(blank=True, related_name='metadata_resources_topic', to='components.codeableconcept')),
                ('useContext', models.ManyToManyField(blank=True, related_name='canonical_resources', to='components.usagecontext')),
                ('versionAlgorithmCoding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_algorithm', to='components.coding')),
            ],
            options={
                'db_table': 'citation',
            },
        ),
        migrations.CreateModel(
            name='CitationClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='citation.citation')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_classification_types', to='components.codeableconcept')),
            ],
            options={
                'db_table': 'citation_classification',
            },
        ),
        migrations.CreateModel(
            name='CitationStatusDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('actual', models.BooleanField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_status_activities', to='components.codeableconcept')),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_dates', to='citation.citation')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_status_dates', to='components.period')),
            ],
            options={
                'db_table': 'citation_status_date',
            },
        ),
        migrations.CreateModel(
            name='CitationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('text', models.TextField()),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='citation.citation')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_summary_styles', to='components.codeableconcept')),
            ],
            options={
                'db_table': 'citation_summary',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('dateAccessed', models.DateTimeField(blank=True, null=True)),
                ('citation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cited_artifact', to='citation.citation')),
            ],
            options={
                'db_table': 'cited_artifact',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('text', models.TextField()),
                ('copyright', models.TextField(blank=True, null=True)),
                ('cited_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='citation.citedartifact')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_abstract_languages', to='components.codeableconcept')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_abstract_types', to='components.codeableconcept')),
            ],
            options={
                'db_table': 'cited_artifact_abstract',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('baseCitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_citations', to='citation.citation')),
                ('cited_artifact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part', to='citation.citedartifact')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_part_types', to='components.codeableconcept')),
            ],
            options={
                'db_table': 'cited_artifact_part',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactPublicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('articleDate', models.DateTimeField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('citedMedium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_mediums', to='components.codeableconcept')),
                ('cited_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_forms', to='citation.citedartifact')),
            ],
            options={
                'db_table': 'cited_artifact_publication_form',
            },
        ),
        migrations.CreateModel(
            name='CitedArtifactPublicationFormPublishedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('publisherLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_in', to='citation.citedartifactpublicationform')),
            ],
            options={
                'db_table': 'cited_artifact_publication_form_published_in',
            },
        ),
    ]
