# Generated by Django 5.2.3 on 2025-09-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citation', '0001_initial'),
        ('components', '0019_duration_reference_relatedartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='citedartifactpublicationformpublishedin',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_in_publishers', to='components.reference'),
        ),
        migrations.AddField(
            model_name='citedartifactpublicationformpublishedin',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_in_types', to='components.codeableconcept'),
        ),
        migrations.AddField(
            model_name='citedartifactrelatesto',
            name='cited_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relates_to', to='citation.citedartifact'),
        ),
        migrations.AddField(
            model_name='citedartifactrelatesto',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_relates_to', to='components.attachment'),
        ),
        migrations.AddField(
            model_name='citedartifactrelatesto',
            name='resourceReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_relates_to', to='components.reference'),
        ),
        migrations.AddField(
            model_name='citedartifactstatusdate',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_artifact_status_activities', to='components.codeableconcept'),
        ),
        migrations.AddField(
            model_name='citedartifactstatusdate',
            name='cited_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_dates', to='citation.citedartifact'),
        ),
        migrations.AddField(
            model_name='citedartifactstatusdate',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_artifact_status_dates', to='components.period'),
        ),
        migrations.AddField(
            model_name='citedartifacttitle',
            name='cited_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='citation.citedartifact'),
        ),
        migrations.AddField(
            model_name='citedartifacttitle',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cited_artifact_title_languages', to='components.codeableconcept'),
        ),
        migrations.AddField(
            model_name='citedartifactversion',
            name='baseCitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_citations', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='citedartifactversion',
            name='cited_artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version', to='citation.citedartifact'),
        ),
        migrations.AddField(
            model_name='citedartifactweblocation',
            name='cited_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_locations', to='citation.citedartifact'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['status'], name='citation_status_c0ff6b_idx'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['date'], name='citation_date_aae75e_idx'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['publisher'], name='citation_publish_7c74e5_idx'),
        ),
    ]
