# Generated by Django 5.2.6 on 2025-09-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0017_virtualservicedetail'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0005_remove_organization_endpoint'),
        ('practitioner', '0005_practitionerrole_endpoint_practitionerrole_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('deceasedBoolean', models.BooleanField(blank=True, null=True)),
                ('deceasedDateTime', models.DateTimeField(blank=True, null=True)),
                ('multipleBirthBoolean', models.BooleanField(blank=True, null=True)),
                ('multipleBirthInteger', models.IntegerField(blank=True, null=True)),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('generalPractitioner', models.ManyToManyField(blank=True, related_name='patients', to='practitioner.practitioner')),
                ('generalPractitionerOrg', models.ManyToManyField(blank=True, related_name='patients', to='organization.organization')),
                ('generalPractitionerRole', models.ManyToManyField(blank=True, related_name='patients', to='practitioner.practitionerrole')),
                ('managingOrganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_patients', to='organization.organization')),
                ('maritalStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_marital_status', to='components.codeableconcept')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('preferred', models.BooleanField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_communications', to='components.codeableconcept')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patient.patient')),
            ],
            options={
                'db_table': 'patient_communication',
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_contacts', to='components.address')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_contacts', to='components.humanname')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_contacts', to='organization.organization')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patient.patient')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_contacts', to='components.period')),
            ],
            options={
                'db_table': 'patient_contact',
            },
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_persons', to='patient.patient')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_persons', to='components.period')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
            ],
            options={
                'db_table': 'related_person',
            },
        ),
        migrations.CreateModel(
            name='PatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('replaced-by', 'Replaced By'), ('replaces', 'Replaces'), ('refer', 'Refer'), ('seealso', 'See Also')], max_length=16)),
                ('other_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='patient.patient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='patient.patient')),
                ('other_related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='patient.relatedperson')),
            ],
            options={
                'db_table': 'patient_link',
            },
        ),
        migrations.CreateModel(
            name='RelatedPersonCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('preferred', models.BooleanField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_person_communications', to='components.codeableconcept')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patient.relatedperson')),
            ],
            options={
                'db_table': 'related_person_communication',
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['active'], name='patient_active_13ddc5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='patient_gender_6b6420_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['birthDate'], name='patient_birthDa_ef6da2_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['active'], name='related_per_active_68d508_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['patient'], name='related_per_patient_86e463_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedperson',
            index=models.Index(fields=['gender'], name='related_per_gender_e4536a_idx'),
        ),
    ]
