# Generated by Django 5.2.6 on 2025-09-07 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('system', models.URLField(blank=True, max_length=512, null=True)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('display', models.CharField(blank=True, max_length=64, null=True)),
                ('userSelected', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coding',
                'indexes': [models.Index(fields=['system'], name='coding_system_89a893_idx'), models.Index(fields=['code'], name='coding_code_ca5106_idx')],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'period',
                'indexes': [models.Index(fields=['start'], name='period_start_f75596_idx'), models.Index(fields=['end'], name='period_end_4aa963_idx')],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('value_string', models.CharField(blank=True, max_length=2048, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('value_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.period')),
            ],
            options={
                'db_table': 'extension',
                'indexes': [models.Index(fields=['url'], name='extension_url_b21829_idx'), models.Index(fields=['content_type', 'object_id'], name='extension_content_df0e3b_idx')],
            },
        ),
    ]
