# Generated by Django 5.2.6 on 2025-09-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('versionId', models.CharField(blank=True, max_length=64, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('source', models.URLField(blank=True, max_length=512, null=True)),
                ('profile', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meta',
                'indexes': [models.Index(fields=['versionId'], name='meta_version_23bb11_idx'), models.Index(fields=['source'], name='meta_source_cd6f26_idx')],
            },
        ),
    ]
