# Generated by Django 5.2.6 on 2025-09-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_metaelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('extensions', 'Extensions'), ('additional', 'Additional'), ('empty', 'Empty')], default='generated', max_length=16)),
                ('div', models.TextField()),
            ],
            options={
                'db_table': 'narrative',
            },
        ),
    ]
