# Generated by Django 5.2.6 on 2025-09-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_narrative'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('comparator', models.CharField(blank=True, choices=[('<', '<'), ('<=', '<='), ('>=', '>='), ('>', '>'), ('ad', 'ad')], max_length=2, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('system', models.URLField(blank=True, max_length=512, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'quantity',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'range',
            },
        ),
        migrations.CreateModel(
            name='UsageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('value_reference_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usage_context',
            },
        ),
        migrations.CreateModel(
            name='CodeableConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('coding', models.ManyToManyField(blank=True, related_name='codeable_concepts', to='components.coding')),
            ],
            options={
                'db_table': 'codeable_concept',
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('system', models.CharField(blank=True, choices=[('phone', 'Phone'), ('fax', 'Fax'), ('email', 'Email'), ('pager', 'Pager'), ('url', 'URL'), ('sms', 'SMS'), ('other', 'Other')], max_length=16, null=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('use', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old'), ('mobile', 'Mobile')], max_length=16, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_points', to='components.period')),
            ],
            options={
                'db_table': 'contact_point',
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('telecom', models.ManyToManyField(blank=True, related_name='contact_details', to='components.contactpoint')),
            ],
            options={
                'db_table': 'contact_detail',
            },
        ),
        migrations.CreateModel(
            name='SimpleQuantity',
            fields=[
                ('quantity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.quantity')),
            ],
            options={
                'db_table': 'simple_quantity',
            },
            bases=('components.quantity',),
        ),
        migrations.AddIndex(
            model_name='quantity',
            index=models.Index(fields=['code'], name='quantity_code_9a1b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='quantity',
            index=models.Index(fields=['system'], name='quantity_system_229a02_idx'),
        ),
        migrations.AddField(
            model_name='usagecontext',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_contexts', to='components.coding'),
        ),
        migrations.AddField(
            model_name='usagecontext',
            name='valueCodeableConcept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_context_values', to='components.codeableconcept'),
        ),
        migrations.AddField(
            model_name='usagecontext',
            name='valueQuantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_context_values', to='components.quantity'),
        ),
        migrations.AddField(
            model_name='usagecontext',
            name='valueRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_context_values', to='components.range'),
        ),
        migrations.AddField(
            model_name='usagecontext',
            name='value_reference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='range',
            name='high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_high', to='components.simplequantity'),
        ),
        migrations.AddField(
            model_name='range',
            name='low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_low', to='components.simplequantity'),
        ),
        migrations.AddIndex(
            model_name='usagecontext',
            index=models.Index(fields=['value_reference_type', 'value_reference_id'], name='usage_conte_value_r_42b7b0_idx'),
        ),
    ]
