# Generated by Django 5.2.6 on 2025-09-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_quantity_range_usagecontext_codeableconcept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('use', models.CharField(blank=True, choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temp'), ('secondary', 'Secondary'), ('old', 'Old')], max_length=16, null=True)),
                ('system', models.URLField(blank=True, max_length=512, null=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'identifier',
            },
        ),
    ]
