# Generated by Django 5.2.6 on 2025-09-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_identifier'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_identifiers', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifiers', to='components.period'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifiers', to='components.codeableconcept'),
        ),
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['system', 'value'], name='identifier_system_2c403b_idx'),
        ),
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['use'], name='identifier_use_62924c_idx'),
        ),
    ]
