# Generated by Django 5.2.6 on 2025-09-08 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_identifier_assigner_identifier_period_and_more'),
        ('organization', '0003_remove_organizationqualification_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='telecom',
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='contact_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='components.contactdetail'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='organization.organizationqualification'),
        ),
    ]
