# Generated by Django 5.2.6 on 2025-09-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_remove_contactdetail_telecom_and_more'),
        ('endpoint', '0004_remove_endpoint_connectiontype_and_more'),
        ('organization', '0004_remove_organization_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeableconcept',
            name='endpoint_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_types', to='endpoint.endpoint'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='endpoint_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_types', to='endpoint.endpoint'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_types', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='endpoint.endpoint'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='endpoint.endpoint'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='organization.organization'),
        ),
    ]
