# Generated by Django 5.2.6 on 2025-09-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_codeableconcept_endpoint_connection_and_more'),
        ('endpoint', '0005_remove_endpointpayload_type_endpoint_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeableconcept',
            name='coding',
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='endpoint_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payload_types', to='endpoint.endpointpayload'),
        ),
        migrations.AddField(
            model_name='coding',
            name='codeable_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codings', to='components.codeableconcept'),
        ),
    ]
