# Generated by Django 5.2.6 on 2025-09-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_remove_codeableconcept_coding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('use', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old'), ('billing', 'Billing')], max_length=16, null=True)),
                ('type', models.CharField(blank=True, choices=[('postal', 'Postal'), ('physical', 'Physical'), ('both', 'Both')], max_length=16, null=True)),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('line', models.JSONField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='HumanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('use', models.CharField(blank=True, choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temp'), ('nickname', 'Nickname'), ('anonymous', 'Anonymous'), ('old', 'Old'), ('maiden', 'Maiden')], max_length=16, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('family', models.CharField(blank=True, max_length=128, null=True)),
                ('given', models.JSONField(blank=True, null=True)),
                ('prefix', models.JSONField(blank=True, null=True)),
                ('suffix', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'human_name',
            },
        ),
    ]
