# Generated by Django 5.2.6 on 2025-09-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_address_humanname'),
        ('practitioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='practitioner.practitioner'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='practitioner.practitioner'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='practitioner_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='practitioner.practitionerqualification'),
        ),
        migrations.AddField(
            model_name='address',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='components.period'),
        ),
        migrations.AddField(
            model_name='address',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='practitioner.practitioner'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_names', to='components.period'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='practitioner.practitioner'),
        ),
    ]
