# Generated by Django 5.2.6 on 2025-09-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_contactpoint_practitioner_identifier_practitioner_and_more'),
        ('practitioner', '0002_practitionerrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeableconcept',
            name='practitioner_role_characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='practitioner.practitionerrole'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='practitioner_role_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='practitioner.practitionerrole'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='practitioner_role_communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='practitioner.practitionerrole'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='practitioner_role_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='practitioner.practitionerrole'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='practitioner_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='practitioner.practitionerrole'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='practitioner_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='practitioner.practitionerrole'),
        ),
    ]
