# Generated by Django 5.2.6 on 2025-09-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_codeableconcept_practitioner_role_characteristic_and_more'),
        ('practitioner', '0004_remove_practitionerrole_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('practitioner_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='practitioner.practitionerrole')),
            ],
            options={
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('daysOfWeek', models.JSONField(blank=True, null=True)),
                ('allDay', models.BooleanField(blank=True, null=True)),
                ('availableStartTime', models.TimeField(blank=True, null=True)),
                ('availableEndTime', models.TimeField(blank=True, null=True)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='components.availability')),
            ],
            options={
                'db_table': 'available_time',
            },
        ),
        migrations.CreateModel(
            name='NotAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('availability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_available_times', to='components.availability')),
                ('during', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='not_available_times', to='components.period')),
            ],
            options={
                'db_table': 'not_available_time',
            },
        ),
    ]
