# Generated by Django 5.2.6 on 2025-09-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_availability_availabletime_notavailabletime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('contentType', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('frames', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='ExtendedContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'extended_contact_detail',
            },
        ),
    ]
