# Generated by Django 5.2.6 on 2025-09-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_attachment_extendedcontactdetail'),
        ('healthcareservice', '0001_initial'),
        ('organization', '0005_remove_organization_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_provision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provision_codes', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_methods', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='healthcare_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_contacts', to='components.address'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='healthcare_service_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_contact_details', to='healthcareservice.healthcareservice'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_contacts', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='organization_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_contact_details', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_contacts', to='components.period'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_contact_purposes', to='components.codeableconcept'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='extended_contact_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='components.extendedcontactdetail'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='extended_contact_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='components.extendedcontactdetail'),
        ),
    ]
