# Generated by Django 5.2.6 on 2025-09-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_availability_healthcare_service_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeableconcept',
            name='location_characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='location.location'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='location_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='location.location'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='location.location'),
        ),
    ]
