# Generated by Django 5.2.6 on 2025-09-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_codeableconcept_location_characteristic_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('addressUrl', models.URLField(blank=True, null=True)),
                ('addressString', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInfo', models.JSONField(blank=True, null=True)),
                ('maxParticipants', models.PositiveIntegerField(blank=True, null=True)),
                ('sessionKey', models.CharField(blank=True, max_length=255, null=True)),
                ('addressContactPoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_service_addresses', to='components.contactpoint')),
                ('addressExtendedContactDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_service_addresses', to='components.extendedcontactdetail')),
                ('channelType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_service_channels', to='components.coding')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_services', to='location.location')),
            ],
            options={
                'db_table': 'virtual_service_detail',
            },
        ),
    ]
