# Generated by Django 5.2.6 on 2025-09-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_virtualservicedetail'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='address',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='patient.relatedperson'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='patient.relatedperson'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='patient_contact_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='patient.patientcontact'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='related_person_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='patient.relatedperson'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='patient_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='patient.patientcontact'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='patient.relatedperson'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='patient.relatedperson'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='patient.relatedperson'),
        ),
    ]
