# Generated by Django 5.2.3 on 2025-09-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0018_address_patient_address_related_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('quantity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.quantity')),
            ],
            options={
                'db_table': 'duration',
            },
            bases=('components.quantity',),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('reference', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('display', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='RelatedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(choices=[('documentation', 'Documentation'), ('justification', 'Justification'), ('citation', 'Citation'), ('predecessor', 'Predecessor'), ('successor', 'Successor'), ('derived-from', 'Derived From'), ('depends-on', 'Depends On'), ('composed-of', 'Composed Of')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=500, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'related_artifact',
            },
        ),
    ]
