# Generated by Django 5.2.3 on 2025-09-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0002_initial'),
        ('components', '0019_duration_reference_relatedartifact'),
        ('encounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='citation_classification_classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='citation.citationclassification'),
        ),
        migrations.AddField(
            model_name='codeableconcept',
            name='citation_current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_states', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='citation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='citation_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='citation_endorser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsers', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='citation_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telecom_points', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='extendedcontactdetail',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_contact_details', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='humanname',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='citation.citation'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='cited_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='citation.citedartifact'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='cited_artifact_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_identifiers', to='citation.citedartifact'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='encounter.encounter'),
        ),
        migrations.AddField(
            model_name='identifier',
            name='published_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='citation.citedartifactpublicationformpublishedin'),
        ),
        migrations.AddField(
            model_name='reference',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='components.identifier'),
        ),
        migrations.AddField(
            model_name='relatedartifact',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_artifacts', to='components.attachment'),
        ),
        migrations.AddField(
            model_name='relatedartifact',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_artifacts', to='components.reference'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['reference'], name='reference_referen_d679bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['type'], name='reference_type_719033_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedartifact',
            index=models.Index(fields=['type'], name='related_art_type_e3be21_idx'),
        ),
    ]
