# Generated by Django 5.2.6 on 2025-09-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0005_identifier'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('mimeType', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'endpoint_payload_element',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('error', 'Error'), ('off', 'Off'), ('entered-in-error', 'Entered In Error'), ('test', 'Test')], max_length=32)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.URLField(max_length=1024)),
                ('header', models.JSONField(blank=True, null=True)),
                ('connectionType', models.ManyToManyField(related_name='endpoint_connections', to='components.codeableconcept')),
                ('contact', models.ManyToManyField(blank=True, related_name='endpoints', to='components.contactpoint')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('environmentType', models.ManyToManyField(blank=True, related_name='endpoint_environments', to='components.codeableconcept')),
                ('identifier', models.ManyToManyField(blank=True, related_name='endpoints', to='components.identifier')),
            ],
            options={
                'db_table': 'endpoint',
            },
        ),
    ]
