# Generated by Django 5.2.6 on 2025-09-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0006_identifier_assigner_identifier_period_and_more'),
        ('endpoint', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='managingOrganization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_endpoints', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='components.period'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative'),
        ),
        migrations.AddField(
            model_name='endpointpayload',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='endpoint_payload_types', to='components.codeableconcept'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='payload',
            field=models.ManyToManyField(blank=True, related_name='endpoints', to='endpoint.endpointpayload'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['status'], name='endpoint_status_f2b04d_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['address'], name='endpoint_address_63d46f_idx'),
        ),
    ]
