# Generated by Django 5.2.6 on 2025-09-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='payload',
        ),
        migrations.AddField(
            model_name='endpointpayload',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='endpoint.endpoint'),
        ),
    ]
