# Generated by Django 5.2.6 on 2025-09-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_remove_endpoint_payload_endpointpayload_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='connectionType',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='environmentType',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='identifier',
        ),
    ]
