# Generated by Django 5.2.6 on 2025-09-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0004_remove_endpoint_connectiontype_and_more'),
        ('organization', '0005_remove_organization_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointpayload',
            name='type',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='organization.organization'),
        ),
    ]
