# Generated by Django 5.2.6 on 2025-09-08 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0005_remove_endpointpayload_type_endpoint_organization'),
        ('practitioner', '0003_practitionerrole_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='practitioner_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='practitioner.practitionerrole'),
        ),
    ]
