# Generated by Django 5.2.6 on 2025-09-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0006_endpoint_practitioner_role'),
        ('healthcareservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='healthcareservice.healthcareservice'),
        ),
    ]
