# Generated by Django 5.2.6 on 2025-09-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_contactpoint_practitioner_identifier_practitioner_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0005_remove_organization_endpoint'),
        ('practitioner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_roles', to='organization.organization')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_roles', to='components.period')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='practitioner.practitioner')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
            ],
            options={
                'db_table': 'practitioner_role',
                'indexes': [models.Index(fields=['active'], name='practitione_active_32eba8_idx'), models.Index(fields=['practitioner'], name='practitione_practit_dd4b13_idx'), models.Index(fields=['organization'], name='practitione_organiz_5c91e0_idx')],
            },
        ),
    ]
