# Generated by Django 5.2.6 on 2025-09-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioner', '0002_practitionerrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerrole',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
