# Generated by Django 5.2.6 on 2025-09-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioner', '0003_practitionerrole_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitionerrole',
            name='availability',
        ),
    ]
