# Generated by Django 5.2.6 on 2025-09-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0007_endpoint_healthcare_service'),
        ('location', '0001_initial'),
        ('practitioner', '0004_remove_practitionerrole_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerrole',
            name='endpoint',
            field=models.ManyToManyField(blank=True, related_name='practitioner_roles', to='endpoint.endpoint'),
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='practitioner_roles', to='location.location'),
        ),
    ]
